#!/bin/bash

## #ddev-generated
## Description: Launch the Vitest-UI.
## Usage: vitest-ui
## Example: "ddev vitest-ui", "ddev vitest-ui -s", "ddev vitest-ui --start"

if ! command -v ./node_modules/.bin/vitest  >/dev/null; then
  echo "Vitest is not available. You may need to install it. Eg. 'npm install -D vitest'"
  exit 1
fi

launch() {
  ddev launch :51204/__vitest__/
}

startUIServer() {
 ddev vitest --ui
}

while [ $# -gt 0 ]; do
  case "$1" in
  -s | --start)
    startUIServer
    shift
    ;;
  esac
  shift
done

launch
