#!/bin/bash

## #ddev-generated
## Description: Helper function for Vitest.
## Usage: vitest [flags] [args]
## Example: "ddev vitest", "ddev vitest --ui"
## ExecRaw: true
## HostWorkingDir: true

if ! command -v /var/www/html/node_modules/.bin/vitest  >/dev/null; then
  echo "Vitest is not available. You may need to install it. Eg. 'npm install -D vitest'"
  exit 1
fi

for arg in "$@"; do
    # Highjack the command to start the UI server
    if [[ "$arg" == "--ui" ]]; then
        # This is the command to that starts the server in a start compatible with DDEV.
        # "--open=false": do NOT open a new browser
        # "--api.strictPort=true": do NOT attempt to find available port
        # "--api.host=0.0.0.0": respond to all host
        /var/www/html/node_modules/.bin/vitest --ui --open=false --api.strictPort=true --api.host=0.0.0.0
        exit 0;
    fi
done

# Pass all flags through to vitest, if `--ui` was NOT included.
/var/www/html/node_modules/.bin/vitest "$@"
